### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jhjacobs81** [AnsgarKlein/Rocket-Launcher#1]
Is this the dock i see in the image? Or that square part?

**Comment by AnsgarKlein** [comment]
It's the square part.
The dock is [docky](https://launchpad.net/docky) which is now [plank](https://launchpad.net/plank) I believe

**Comment by jhjacobs81** [comment]
I was afraid you where gonna say that ;-) 

Still, can your app be installed on a debian based distro? I assume yes?

**Comment by AnsgarKlein** [comment]
There are no binary packages but you could compile from source. Have a look at the [INSTALL.md](https://github.com/AnsgarKlein/Rocket-Launcher/blob/main/INSTALL.md) file for that.

The last time I worked on Rocket-Launcher was in 2014 so I am not sure how well it works with newer versions of Gtk 3 or other modern technologies like Wayland.
